### ISSUE TITLE
search oyatillo

### ISSUE THREAD

**Issue by javohirbekkhaydarov** [AxadjonovOyatillo21/TodoServiceNP#1]
Assalomu Aleykum Oyatillo biz sizni xo`p izladik qaydasiz telegramdan yozin username o`sha o`sha  https://t.me/InshaAllah_FullStack_Developer yoki telegram usernameyingizni bering

**Comment by AxadjonovOyatillo21** [comment]
> Assalomu Aleykum Oyatillo biz sizni xo`p izladik qaydasiz telegramdan yozin username o`sha o`sha https://t.me/InshaAllah_FullStack_Developer yoki telegram usernameyingizni bering

Va alaykum assalam! Telegram yo'q.
